python-trio/trio-websocket

examples/server.py
trio_websocket/__init__.py

* listen() supports nursery start() protocol so we can
block on server being ready for connections
* port is read back from the socket and exposed via property
so we can let OS select port (via port=0)
* remove listen() KeyboardInterrupt handling and suppression
Fixes #8 and #6.

WebSocketServer improvements:

---

.gitignore
README.md
examples/client.py
pytest.ini
setup.py
tests/test_connection.py
trio_websocket/__init__.py

Would appreciate your feedback, @belm0 and @njsmith, if you have the time.

WebSocketConnection now inherits AsyncResource

---

examples/server.py
setup.py
tests/test_connection.py
trio_websocket/__init__.py

This implements #2 with the following features:
* Handle multiple listeners correctly: before this PR, if you had multiple listeners, i.e. `host=None` and you get an IPv4 listener and an IPv6 listener, then the log message would only show the first listener and the `port` property would only work on the first listener. Now multiple listeners are logged correctly and a new `listeners` property exposes metadata about each listener. The old `port` property is still there for convenience when using a single TCP listener.
* Factor listener out of server code: the server now takes a list of listeners instead of host/port/etc. A new `serve_tcp()` function takes host/port/etc. and constructs a server instance.
* Add functions that take an arbitrary stream and wrap them in a `WebSocketConnection`.

Arbitrary listeners and streams

---

trio_websocket/__init__.py

Requires trio 0.8.0.
Fixes #39.

trio.BrokenStreamError -> BrokenResourceError

---

tests/test_connection.py

test uses explicit import from trio-websocket

have server handler exit test verify client-side close reason;

---

examples/client.py

This is the second attempt at this. Instead of modifying
trio-websocket to support cancelling a handler, this commit
modifies only the example client itself: it now has one task
that gets messages and prints them, and a second task that
gets user input and sends messages/commands/etc.
This supersedes #48.

Example client exits on ConnectionClosed (#22)

---

README.md
examples/client.py
tests/test_connection.py
trio_websocket/__init__.py

This PR implements ping/pong behavior similar to aaugustin's websocket library. A call to `ping()` waits for a response with the same payload. (An exception is raised if the payload matches a ping that's already in flight.) A payload is randomly generated if omitted by the caller. Add a new `pong()` method that can be used for sending an unsolicited pong.

Improve ping v2

---

README.md
examples/server.py
tests/test_connection.py
trio_websocket/__init__.py

First attempt at this. Server handlers now receive a WebSocketRequest
instead of a WebSocketConnection. The request object provides the
client's handshake parameters and allows the server to finalize
handshake parameters. The server calls the requests ``accept()``
method to finish the handshake and obtain a connection object.
This first version exposes the request URL, headers, and subprotocols
to the server. The server is allowed to select a subprotocol. In future
versions (given support in wsproto), we can expand the request object
to customize headers and choose extensions.
In addition, the tests are updated: one new test to cover the
selection of a subprotocol, plus updates to existing tests to handle
the new request->connection step.
Finally, the README and example server are updated …

Allow more control over handshake (#4)

---

tests/test_connection.py
trio_websocket/_impl.py

As described in the issue, get_message() was raising connection closed
even if there were pending messages. Per Nathaniel's suggestion, the
proper behavior is this:
1. If the remote endpoint closed the connection, then the local endpoint
may continue reading all messages sent prior to closing.
2. If the local endpoint closed the connection, then the local endpoint
may not read any more messages.
I added tests for these two conditions and implemented the behavior by
closing the ReceiveChannel inside the connection's `aclose()`. This
requires a bit of additional exception handling inside `get_message()`
and inside the reader task.
One slight surprise is that the test couldn't be written due to the bug
in #74! The client would hang because the reader task is blocked by
the unconsumed …

Delay connection closed (#69)

---

docs/index.rst
docs/recipes.rst
docs/servers.rst
docs/timeouts.rst
tests/test_connection.py
trio_websocket/_impl.py

This includes tests and docs.
I also started thinking about how to make tests more deterministic, i.e. #88. I don't have a full solution to that here, but I did write these new tests more carefully and included some comments on the test module that should guide additional effort to reduce race conditions in the test.

Implement timeouts (#64)

---

setup.py
tests/test_connection.py
trio_websocket/_impl.py

Remove references to the deprecated trio.ssl

---

setup.py
tests/test_connection.py
trio_websocket/_impl.py

Changes in this PR:
* Use `send()` instead of separate `send_message()`, `ping()`, etc.
* The `send()` method directly returns bytes to send; do not call `bytes_to_send()` anymore.
* `receive_bytes()` is called `receive_data()`
* Close and ping don't generate responses automatically; must explicitly send a response.
* Connection handshake API is slightly different.
All tests pass. Coverage remains at 93%. I have aimed only to consume the new API, but not to implement any refactorings or new features that this new API will enable.

Consume the new API in wsproto==0.14.0

---

docs/api.rst
tests/test_connection.py
trio_websocket/_impl.py

This exposes the IP address and port number for the local and
remote sockets.
`ListenPort` is renamed to `Endpoint` and used as the data class
for the endpoints exposed by `WebSocketRequest` and
`WebSocketConnection`.

Add metadata for WebSocket endpoints (closes #108)

---

docs/api.rst
tests/test_connection.py
trio_websocket/__init__.py
trio_websocket/_impl.py

Adds a `reject()` method to the request class. Since this new method has an `extra_headers` argument, I also added `extra_headers` to `accept()` for symmetry. (Not exactly what was requested in #110 but definitely related.)

Add support for rejecting connection (#107)

---

.travis.yml
setup.py

* add to continuous build
* exclude wsaccel dependency
Closes #119.

pypy support

---

tests/test_connection.py
trio_websocket/__init__.py

import Endpoint into the trio_websocket module

---

trio_websocket/_impl.py

Matching existing documentation on `serve_websocket()`

document WebSocketServer.run usage and start() return type

---

autobahn/client.py
autobahn/server.py
docs/conf.py
examples/client.py
requirements-dev.txt
setup.py
tests/test_connection.py
trio_websocket/_impl.py

The first two commits fix some deprecations; since they are only in the tests I didn't bother with backward compatibility with older trio/attrs versions.
The next commits remove the ipaddress, wsaccel and yarl dependencies, please see the commit messages for details.
Once Python 3.5 is dropped can also remove the async_generator dep I think, which will leave only trio and wsproto.

Fix some deprecations in tests + remove some dependencies

---

tests/test_connection.py
trio_websocket/_impl.py

(see https://github.com/python-trio/trio/issues/1559)

avoid contributing to dropped exceptions during finalization

---

tests/test_connection.py
trio_websocket/_impl.py

Fixes #148.
This regressed in 0233e2176731a190a515c025c0762c19f (version 0.9.0) due
to different behavior between yarl and urllib.parse.urlsplit on a URL
without a path component like "wss://ws.kraken.com". yarl makes this `/`
while urlsplit makes it ''. h11 expects `/` as specified in the quoted
RFC.

Fix " Illegal target characters" when connecting to URL with zero-length path

---

Makefile
tests/test_connection.py
trio_websocket/_impl.py

server: close TCP connection after CloseConnection event

---

MANIFEST.in

Thank you for `trio-websocket`!
This PR ensures the `LICENSE` file is included in `sdist` distributions, which, while not _required_ by the terms of the MIT license, is helpful for downstreams.
In my case, I'm looking to package this for conda-forge, which generally requires _some_ license documentation for all packages. We're not blocked, as such, as we can source it from github from the same tag, but keeping everything in one tarball makes things a bit more reliable.
Thanks again!

include LICENSE in source distributions

---

README.md

The latest version of ``trio-websocket`` just bumped the minimum version of Python to ``3.7``, but the README.md still shows an outdated version.

Set minimum Python version to 3.7 in README.md

---

tests/test_connection.py
trio_websocket/_impl.py

During a local-initiated close handshake, the following incorrect behavior was observed:
* `closed` attribute would be `None`
* `get_message()` would be silently ignored (wsproto < 0.2.0) or leak a `LocalProtocolException` (wsproto >= 0.2.0)
Upon local-initiated close, `closed` will now have the reason, and `get_message()` will raise `ConnectionClosed`.
Fixes #158.

fix reason not being set after local close

---

tests/test_connection.py
trio_websocket/_impl.py

Bad ordering:
1. Remote close
2. TCP closed
3. Local confirms
=> no ConnectionClosed raised, client hangs forever

Fix a hang when the remote hangs up rudely

---

.github/workflows/ci.yml
requirements-dev.txt
setup.py
trio_websocket/_impl.py

I wrote this ... and then I saw the discussion in #180 
So this is kind of a duplicate of that, except I also updated CI to test it, and general compatibility with 3.11/3.12, as well as pypy3.9 and pypy3.10.
I don't think there's any reason *not* to update so as not to require `exceptiongroup` on py3.11+, [and it mirrors python-trio/trio](https://github.com/python-trio/trio/blob/master/setup.py#L96).
pypy3.9 and pypy3.10 are the [currently supported versions of python](https://doc.pypy.org/en/latest/release-v7.3.12.html)
As mentioned in the comment in `ci.yml`, running `pylint` on 3.12 crashes, see https://github.com/pylint-dev/pylint/issues/8782

add py3.11+3.12 and pypy3.9+3.10 to CI, conditionally require exceptiongroup

---

.github/workflows/ci.yml
Makefile
README.md
requirements-dev-full.txt
requirements-dev.in
requirements-dev.txt
requirements-extras.in
setup.py
tests/test_connection.py
trio_websocket/_impl.py

Split out from #188 with a `--patch` checkout. This does destroy the commit history, so I might need to rewrite the history in #188 to avoid conflicts.
* Drops python3.7 support. It still works afaik, but is a pain to test in CI.
* Adds loose mypy run to Makefile & CI
* Adds some type annotations
* ~~Adds 3.13-dev test run. It currently fails, but will pass once trio and cffi push new releases.~~
* Adds blurb to readme on status of the project.
* Bump package versions in requirements-dev.txt and requirements-dev-full.txt
* Adds small tests to slightly bump code coverage

drop 3.7, add mypy test, bump reqs, etc

---

tests/test_connection.py
trio_websocket/_impl.py

fixes #191 
I'm not 100% sure that `copy_exc` is 100% robust (given that everything seems ever so fickle with copying exceptions), so it may be a good idea to wrap it in a `try: except` that gives up on copying if anything fails.

fix loss of context/cause on exceptions raised inside open_websocket

---

trio_websocket/_impl.py

Prior to https://github.com/python-trio/trio-websocket/commit/49b93c1b5a7977b5e37b6b16650b6a41c2064f98, `_url_to_host()` modified `ssl_context` according to whether the URL contained `ws` or `wss`. That commit introduced `return_ssl_context` because the return value has a different type set (`ssl.SSLContext | bool`) than the passed in argument (`ssl.SSLContext | None`). But the determination of which port number to use was still based on `ssl_context`, which would result in port 80 being used in the case where the user passed in a `wss://` URL without an SSLContext. Checking `return_ssl_context` instead results in the correct behavior.

Use correct port for wss URLs when ssl_context is None
